### ISSUE TITLE
(v1.0) Broken link

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI-522_Titanic-Survival-Prediction#53]
link to "src" is broken on the project's README.

**Comment by aldenchen** [comment]
The `src` link from last week linked to a file called `load-training-data.py`, which  only read in a `.csv` file using `pd.read_csv`. The file is still in the src folder in the v1.0 release. We removed that file from the repository this week since it was replaced by a file called `cleaning.py`, which loads the data, does some cleaning, and outputs a cleaned `.csv` file.  As such, the link no longer works.
